In [1]:
"""
Santiago de Cali, Gennaio, 11, 2021
OpenWebinars - Analisi dei Dati con Pandas e NumPy

**NumPy**

- Riferimenti: https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/
"""
import sys
!conda install --yes --prefix {sys.prefix} numpy


EnvironmentLocationNotFound: Not a conda environment: C:\Program



In [2]:
import numpy as np

In [3]:
array_uno = np.array([5,6,9])

In [4]:
array_uno

array([5, 6, 9])

In [5]:
matrice_numerica = np.array([[1,0,0], [0,1,0], [0,0,1]])

In [6]:
matrice_numerica

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
np.arange(0,25,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(start=0, stop=35, num=10) # grafica

array([ 0.        ,  3.88888889,  7.77777778, 11.66666667, 15.55555556,
       19.44444444, 23.33333333, 27.22222222, 31.11111111, 35.        ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(5,5)

array([[0.43324629, 0.13369011, 0.53839725, 0.80255519, 0.05204021],
       [0.36824807, 0.93078717, 0.43143222, 0.64766516, 0.51288531],
       [0.09275823, 0.1085188 , 0.66786869, 0.6291366 , 0.02769583],
       [0.21698261, 0.34356157, 0.38285539, 0.67434941, 0.9992762 ],
       [0.7565516 , 0.18211418, 0.58867289, 0.22728839, 0.2105815 ]])

In [21]:
np.random.randn(30) # Distribuzione normale

array([ 1.57537521, -1.42991616,  1.28190161,  1.39683856, -0.23695561,
        1.00475659,  0.03242412,  1.33999087, -0.02909332,  0.94246694,
        0.69922674,  1.22899585,  0.68234128, -0.51135312,  1.85849017,
       -0.48550927, -0.09605286,  0.52428446, -0.48007187,  0.1452564 ,
        0.4310877 , -1.09362454, -1.22355597,  0.28393321,  0.8889618 ,
       -2.36963258,  1.22345349,  0.08113258, -0.27560573,  0.46482215])

In [22]:
np.random.randn(3,10) # Distribuzione normale

array([[ 1.02468984,  0.03570052, -0.52032661, -0.71368593,  0.1804988 ,
        -0.63275476,  0.37131736, -0.74513517,  1.35484497,  0.08292568],
       [ 0.61743501, -0.25638818,  1.30951597, -0.34720715, -0.34605177,
         1.18587077, -0.23354316, -0.45924904, -0.48655464,  0.10379025],
       [-1.15547167, -0.16843481,  0.77809033, -1.15138072,  2.88995368,
        -2.43614909, -0.35489361, -1.42309295,  1.19553567,  1.49761196]])

In [24]:
np.random.randint(low = 100, high = 495, size = 10)# Problemi dei prezzi

array([190, 471, 351, 128, 137, 119, 149, 249, 297, 139])